[workspace]
resolver = "3"
members = ["mesh", "router", "roadwarriors", "nftables", "common"]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Evgeniy Slizevich <evgeniy@slizevich.net>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/ffaxl/slipmesh-operators"

[workspace.dependencies]
common = { path = "common" }

anyhow = "1.0.104"
base64 = "0.23.0"
futures = "0.3.33"
k8s-openapi = { version = "0.28.0", features = ["v1_36", "schemars"] }
kube = { version = "4.2.0", default-features = false, features = ["client", "rustls-tls", "aws-lc-rs", "runtime", "derive"] }
reqwest = { version = "0.13.4", default-features = false, features = ["rustls", "json"] }
schemars = "1.2.2"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
serde_yaml = "0.9.34"
thiserror = "2.0.19"
tokio = { version = "1.53.1" }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

genetlink = "0.2.6"
netlink-packet-amnezia-wireguard = "0.1.2"
netlink-packet-core = "0.8.1"
netlink-packet-generic = "0.4.0"
netlink-packet-route = "0.30.0"
rtnetlink = "0.21.0"
